CREATE TABLE Products (
  id INT IDENTITY(1,1) PRIMARY KEY,
  sku NVARCHAR(64) NULL,
  name NVARCHAR(200) NOT NULL,
  description NVARCHAR(MAX) NULL,
  price DECIMAL(10,2) NOT NULL DEFAULT 0,
  quantity INT NOT NULL DEFAULT 0,
  created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  updated_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  row_version ROWVERSION
);

CREATE TABLE InventoryTransactions (
  id INT IDENTITY(1,1) PRIMARY KEY,
  product_id INT NOT NULL FOREIGN KEY REFERENCES Products(id),
  type NVARCHAR(10) NOT NULL, -- 'in' or 'out'
  qty INT NOT NULL,
  note NVARCHAR(500) NULL,
  created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE [Users] (
  id INT IDENTITY(1,1) PRIMARY KEY,
  email NVARCHAR(255) NOT NULL UNIQUE,
  password_hash NVARCHAR(255) NOT NULL,
  display_name NVARCHAR(200) NULL,
  role NVARCHAR(50) DEFAULT 'user',
  created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);
